version: "0.2"
language: en
words:
  - argnames
  - argvalues
  - automodule
  - bndy
  - bugprone
  - bysource
  - caplog
  - capsys
  - codecov
  - codespell
  - consts
  - cppcoreguidelines
  - cstdio
  - declval
  - docutils
  - endfor
  - endgroup
  - endmacro
  - Fixit
  - fontawesome
  - gitmodules
  - gmtime
  - intersphinx
  - iomanip
  - keepends
  - levelno
  - libgit
  - libvips
  - markdownlint
  - maxsplit
  - mktime
  - mypy
  - posargs
  - posix
  - pybind
  - pygit
  - pypi
  - pyproject
  - pytest
  - ratelimit
  - revparse
  - seealso
  - setenv
  - shenxianpeng
  - srcdir
  - stddef
  - tada
  - timeit
  - toctree
  - tofile
  - tomli
  - topo
  - undoc
  - urllib
  - vararg
  - venv
  - viewcode
  - virtualenv
  - zizmor
ignorePaths:
  - .env/**
  - .venv/**
  - env/**
  - venv/**
  - tests/**/*.{json,h,c,cpp,hpp,patch,diff}
  - "**.clang-tidy"
  - "**.clang-format"
  - pyproject.toml
  - .gitignore
  - "**/*.{yml,yaml,txt}"
  - CHANGELOG.md
