name: Summarize unreleased changes

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions: {}

jobs:
  summarize-unreleased:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
      - name: Run git-cliff
        env:
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_REPO: ${{ github.repository }}
          GIT_CLIFF_CONFIG: .github/cliff.toml
          UV_CONSTRAINT: .github/requirements.txt
        run: >-
          uvx
          git-cliff
          --unreleased
          --bump
          --output
          "${GITHUB_STEP_SUMMARY}"
          --strip
          header
